# Generated by Django 6.0.6 on 2026-08-19 15:43

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره تماس')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='تصویر پروفایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(max_length=255, verbose_name='شناسه (تلفن/ایمیل)')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'درخواست کد یکبار مصرف',
                'verbose_name_plural': 'درخواست\u200cهای کدهای یکبار مصرف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'is_used', 'expires_at'], name='users_otpre_identif_f1bedf_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('country', models.CharField(db_comment='Country of the address.', help_text='The country where the address is located.', max_length=100, verbose_name='Country')),
                ('province', models.CharField(db_comment='Province or state of the address.', help_text='The province, state, or regional division of the address.', max_length=100, verbose_name='Province')),
                ('city', models.CharField(db_comment='City or town of the address.', help_text='The city or town of the address.', max_length=100, verbose_name='City')),
                ('postal_address', models.TextField(db_comment='Full detailed postal address.', help_text='The full postal address, including street name, number, and any additional details.', verbose_name='Postal Address')),
                ('postal_code', models.CharField(db_comment='Postal or ZIP code of the address.', help_text='The postal or ZIP code for the address.', max_length=20, verbose_name='Postal Code')),
                ('plaque', models.CharField(db_comment='Plaque number of the building or house.', help_text='The specific plaque number of the building or house.', max_length=20, verbose_name='Plaque')),
                ('building_unit', models.CharField(blank=True, db_comment='Unit or apartment number in a building, optional.', help_text='The unit or apartment number within a building, if applicable.', max_length=20, null=True, verbose_name='Building Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A universally unique identifier (UUID) automatically generated for this content. This identifier is used as the unique primary key and should not be modified manually.', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='مثال: خانه، محل کار', max_length=100, verbose_name='عنوان آدرس')),
                ('recipient_first_name', models.CharField(max_length=150, verbose_name='نام تحویل گیرنده')),
                ('recipient_last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی تحویل گیرنده')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='شماره تماس تحویل گیرنده')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس\u200cهای کاربران',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='users_usera_user_id_b870fc_idx'),
        ),
    ]
