#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

python /wait_for_deps.py

rm -f /app/celerybeat/celerybeat.pid

exec celery -A arkkala beat \
    --loglevel=info \
    --pidfile=/app/celerybeat/celerybeat.pid \
    --schedule=/app/celerybeat/celerybeat-schedule