from typing import Protocol, Optional, Any, Tuple
from django.db.models import QuerySet

class UserRepositoryPort(Protocol):
    """
    Abstract contract ensuring database operations concerning users remain isolated.
    """
    def get_by_email(self, email: str) -> Optional[Any]: ...
    def get_or_create_by_phone(self, phone: str) -> Tuple[Any, bool]: ...
    def save_user(self, user: Any) -> None: ...

class OTPRepositoryPort(Protocol):
    """
    Abstract contract defining temporary token rate-limits and persistence.
    """
    def get_valid_otp(self, identifier: str, code: str) -> Optional[Any]: ...
    def count_requests_since(self, identifier: str, since: Any) -> int: ...
    def get_latest_request(self, identifier: str) -> Optional[Any]: ...
    def save_request(self, request: Any) -> None: ...
    def mark_as_used(self, request: Any) -> None: ...
    def delete_request(self, request: Any) -> None: ...
    def delete_by_uuid(self, uuid: Any) -> None: ...

class AddressRepositoryPort(Protocol):
    """
    Abstract contract resolving address logistics operations explicitly.
    """
    def get_user_addresses(self, user: Any) -> QuerySet: ...
    def set_default_address(self, user_id: Any, address_uuid: Any) -> None: ...