FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY arkkala/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./arkkala /app